### PR TITLE
add PrivacyManifest

### PR DESCRIPTION
**Pull request by fastlaneDeveloper**

### CODE REVIEW

**Comment by fastlaneDeveloper** [comment]
add PrivacyManifest

**Comment by fastlaneDeveloper** [comment]
add PrivacyManifest

**Comment by fastlaneDeveloper** [comment]
add PrivacyManifest

**Comment by fastlaneDeveloper** [comment]
add PrivacyManifest

**Comment by fastlaneDeveloper** [comment]
add PrivacyManifest

**Comment by fastlaneDeveloper** [comment]
add PrivacyManifest

**Comment by xcibik00** [comment]
Hi @fastlaneDeveloper , its already available from 2.25.0 (resp. 2.25.2) version
Do you have problem with integration of it? 
Please let us know

**Pull request closed without merging**
