### PR TITLE
Fix Carthage integration

### PR DESCRIPTION
**Pull request by olejnjak**
As Carthage uses xcodeproj file, that is committed in repository, it needs to be set up correctly.

Current project file caused bunch of [warnings](https://github.com/exponea/exponea-ios-sdk/files/10403493/warnings.txt) in console to appear - reason is that in project file there is SwiftSoup as SPM dependency, which is static. That means that once ExponeaSDK is linked to app, SwiftSoup is present twice, once in the app and once in ExponeaSDK. This could even lead to issues in case that SPM dependency is different version from binary built by Carthage.

This PR fixes this integration by linking SwiftSoup through Carthage without embedding it to ExponeaSDK target as embedding it is app's responsibility.

I also deleted committed SwiftSoup binary as I think that there is no reason to have it there.

### CODE REVIEW

**Comment by olejnjak** [comment]
Hello? 👋

**Comment by adam1929** [comment]
Thank you for your PR. We are currently working on carthage/spm/cocoapods integration fix.

**Comment by olejnjak** [comment]
Okay and is there any estimate?

**Comment by xcibik00** [comment]
Hi @olejnjak, it will be a part of next iOS release

**Pull request closed without merging**
